name: Build and deploy container app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    name: Build and Deploy Job
    environment: production_azure_webapp

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/
          username: ${{ secrets.ACR_USER_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/${{ secrets.ACR_REGISTRY_NAME }}/${{ vars.PROJECT}}:${{ github.sha }}
          file: Dockerfile

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ vars.PROJECT}}"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISH_PROFILE }}
          images: "${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/${{ secrets.ACR_REGISTRY_NAME }}/${{ vars.PROJECT}}:${{ github.sha }}"
