name: Linux Container Node Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.APP_SERVICE_APP_NAME }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.APP_SERVICE_APP_NAME }}:${{ github.sha }}

      # - uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: "${{ secrets.APP_SERVICE_APP_NAME }}"
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     images: "${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.APP_SERVICE_APP_NAME }}:${{ github.sha }}"
